// <auto-generated />
namespace MVCInventory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addemployeeindex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addemployeeindex));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191338556_addemployeeindex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
